In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler, LabelEncoder
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import warnings 
warnings.filterwarnings('ignore')

In [15]:
data = pd.read_csv(r"C:\Users\sangm\Documents\Alphabets_data.csv")
data.head(3)

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9

# 1. Data Exploration and Preprocessing:

In [16]:
# Display basic information about the dataset
print("data Info:")
print(data.info())

data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64
 2   ybox    20000 non-null  int64
 3   width   20000 non-null  int64
 4   height  20000 non-null  int64
 5   onpix   20000 non-null  int64
 6   xbar    20000 non-null  int64
 7   ybar    20000 non-null  int64
 8   x2bar   20000 non-null  int64
 9   y2bar   20000 non-null  int64
 10  xybar   20000 non-null  int64
 11  x2ybar  20000 non-null  int64
 12  xy2bar  20000 non-null  int64
 13  xedge   20000 non-null  int64
 14  xedgey  20000 non-null  int64
 15  yedge   20000 non-null  int64
 16  yedgex  20000 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB
None

In [17]:
data.shape

(20000, 17)

In [20]:
print("\data Summary:")
print(data.describe())
print("\nFirst Few Rows:")

\data Summary:
               xbox          ybox         width       height         onpix  \
count  20000.000000  20000.000000  20000.000000  20000.00000  20000.000000
mean       4.023550      7.035500      5.121850      5.37245      3.505850
std        1.913212      3.304555      2.014573      2.26139      2.190458
min        0.000000      0.000000      0.000000      0.00000      0.000000
25%        3.000000      5.000000      4.000000      4.00000      2.000000
50%        4.000000      7.000000      5.000000      6.00000      3.000000
75%        5.000000      9.000000      6.000000      7.00000      5.000000
max       15.000000     15.000000     15.000000     15.00000     15.000000

               xbar          ybar         x2bar         y2bar         xybar  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.000000
mean       6.897600      7.500450      4.628600      5.178650      8.282050
std        2.026035      2.325354      2.699968      2.380823      2.488475
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        6.000000      6.000000      3.000000      4.000000      7.000000
50%        7.000000      7.000000      4.000000      5.000000      8.000000
75%        8.000000      9.000000      6.000000      7.000000     10.000000
max       15.000000     15.000000     15.000000     15.000000     15.000000

            x2ybar        xy2bar         xedge        xedgey         yedge  \
count  20000.00000  20000.000000  20000.000000  20000.000000  20000.000000
mean       6.45400      7.929000      3.046100      8.338850      3.691750
std        2.63107      2.080619      2.332541      1.546722      2.567073
min        0.00000      0.000000      0.000000      0.000000      0.000000
25%        5.00000      7.000000      1.000000      8.000000      2.000000
50%        6.00000      8.000000      3.000000      8.000000      3.000000
75%        8.00000      9.000000      4.000000      9.000000      5.000000
max       15.00000     15.000000     15.000000     15.000000     15.000000

            yedgex
count  20000.00000
mean       7.80120
std        1.61747
min        0.00000
25%        7.00000
50%        8.00000
75%        9.00000
max       15.00000

First Few Rows:

In [22]:
print(data.head())

  letter  xbox  ybox  width  height  onpix  xbar  ybar  x2bar  y2bar  xybar  \
0      T     2     8      3       5      1     8    13      0      6      6
1      I     5    12      3       7      2    10     5      5      4     13
2      D     4    11      6       8      6    10     6      2      6     10
3      N     7    11      6       6      3     5     9      4      6      4
4      G     2     1      3       1      1     8     6      6      6      6

   x2ybar  xy2bar  xedge  xedgey  yedge  yedgex
0      10       8      0       8      0       8
1       3       9      2       8      4      10
2       3       7      3       7      3       9
3       4      10      6      10      2       8
4       5       9      1       7      5      10

In [21]:
#checking for missing value
missing_values = data.isnull().sum()
missing_values

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [23]:
#check for duplicates
data.duplicated().sum()

1332

In [24]:
#remove duplicate data
data = data.drop_duplicates()

In [25]:
data.duplicated().sum()

0

# 2. Model Implementation:

In [29]:
x = data.drop(columns=['letter'])
y = data['letter']

In [30]:
# Minmax scaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)
pd.DataFrame(x_scaled)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.133333,0.533333,0.200000,0.333333,0.066667,0.533333,0.866667,0.000000,0.400000,0.400000,0.666667,0.533333,0.000000,0.533333,0.000000,0.533333
1,0.333333,0.800000,0.200000,0.466667,0.133333,0.666667,0.333333,0.333333,0.266667,0.866667,0.200000,0.600000,0.133333,0.533333,0.266667,0.666667
2,0.266667,0.733333,0.400000,0.533333,0.400000,0.666667,0.400000,0.133333,0.400000,0.666667,0.200000,0.466667,0.200000,0.466667,0.200000,0.600000
3,0.466667,0.733333,0.400000,0.400000,0.200000,0.333333,0.600000,0.266667,0.400000,0.266667,0.266667,0.666667,0.400000,0.666667,0.133333,0.533333
4,0.133333,0.066667,0.200000,0.066667,0.066667,0.533333,0.400000,0.400000,0.400000,0.400000,0.333333,0.600000,0.066667,0.466667,0.333333,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18663,0.333333,0.533333,0.466667,0.466667,0.466667,0.466667,0.600000,0.266667,0.533333,0.466667,0.466667,0.533333,0.200000,0.666667,0.533333,0.400000
18664,0.133333,0.133333,0.200000,0.200000,0.133333,0.466667,0.466667,0.466667,0.400000,0.400000,0.400000,0.266667,0.133333,0.533333,0.200000,0.466667
18665,0.466667,0.666667,0.533333,0.533333,0.266667,0.266667,0.533333,0.400000,0.600000,0.800000,0.600000,0.866667,0.133333,0.600000,0.200000,0.466667
18666,0.400000,0.600000,0.400000,0.466667,0.333333,0.400000,0.733333,0.200000,0.466667,0.733333,0.600000,0.333333,0.133333,0.800000,0.133333,0.266667
18667,0.266667,0.600000,0.400000,0.400000,0.133333,0.600000,0.333333,0.200000,0.066667,0.533333,0.066667,0.533333,0.133333,0.466667,0.133333,0.533333

In [31]:
# One-hot encode the target variable
encoder = OneHotEncoder()
y_en = encoder.fit_transform(y.values.reshape(-1, 1))
y_encoded = pd.DataFrame(y_en.toarray())

In [32]:
y_encoded

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18663,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18664,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18665,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18667,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Splitting into Training and Test Sets

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

In [40]:
model1 = Sequential([
    Dense(12, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='softmax')
])

# since its a multiclass classification problem so im using relu for hidden layer and softmax for output layer

In [41]:
model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
#I'm using adam optimizer bcz it uses both adagrad and rmsprop properties

In [42]:
training = model1.fit(x_train, y_encoded, epochs=20, batch_size=20, validation_split=0.2)

Epoch 1/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0422 - loss: 3.2595 - val_accuracy: 0.0422 - val_loss: 3.2575
Epoch 2/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0407 - loss: 3.2560 - val_accuracy: 0.0382 - val_loss: 3.2574
Epoch 3/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0425 - loss: 3.2555 - val_accuracy: 0.0412 - val_loss: 3.2574
Epoch 4/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0445 - loss: 3.2553 - val_accuracy: 0.0449 - val_loss: 3.2581
Epoch 5/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0343 - loss: 3.2543 - val_accuracy: 0.0395 - val_loss: 3.2576
Epoch 6/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0422 - loss: 3.2554 - val_accuracy: 0.0418 - val_loss: 3.2576
Epoch 7/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0443 - loss: 3.2548 - val_accuracy: 0.0435 - val_loss: 3.2574
Epoch 8/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0405 - loss: 3.2534 - val_accuracy: 0.0432 - val_loss: 3.2577
Epoch 9/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0446 - loss: 3.2554 - val_accuracy: 0.0435 - val_loss: 3.2580
Epoch 10/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0425 - loss: 3.2520 - val_accuracy: 0.0445 - val_loss: 3.2575
Epoch 11/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0469 - loss: 3.2523 - val_accuracy: 0.0425 - val_loss: 3.2586
Epoch 12/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0451 - loss: 3.2524 - val_accuracy: 0.0432 - val_loss: 3.2578
Epoch 13/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0442 - loss: 3.2512 - val_accuracy: 0.0405 - val_loss: 3.2580
Epoch 14/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0504 - loss: 3.2505 - val_accuracy: 0.0449 - val_loss: 3.2583
Epoch 15/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0469 - loss: 3.2509 - val_accuracy: 0.0425 - val_loss: 3.2580
Epoch 16/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0445 - loss: 3.2516 - val_accuracy: 0.0459 - val_loss: 3.2587
Epoch 17/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0436 - loss: 3.2513 - val_accuracy: 0.0432 - val_loss: 3.2590
Epoch 18/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0460 - loss: 3.2498 - val_accuracy: 0.0415 - val_loss: 3.2583
Epoch 19/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0440 - loss: 3.2504 - val_accuracy: 0.0385 - val_loss: 3.2592
Epoch 20/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0494 - loss: 3.2503 - val_accuracy: 0.0385 - val_loss: 3.2586

# 3. Hyperparameter Tuning:

In [43]:
model2 = Sequential([
    Dense(56, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model2.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model2.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

Epoch 1/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0389 - loss: 3.2643 - val_accuracy: 0.0368 - val_loss: 3.2581
Epoch 2/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0407 - loss: 3.2570 - val_accuracy: 0.0402 - val_loss: 3.2561
Epoch 3/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0451 - loss: 3.2556 - val_accuracy: 0.0405 - val_loss: 3.2570
Epoch 4/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0421 - loss: 3.2553 - val_accuracy: 0.0392 - val_loss: 3.2567
Epoch 5/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0376 - loss: 3.2550 - val_accuracy: 0.0415 - val_loss: 3.2568
Epoch 6/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0438 - loss: 3.2539 - val_accuracy: 0.0375 - val_loss: 3.2575
Epoch 7/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0447 - loss: 3.2528 - val_accuracy: 0.0398 - val_loss: 3.2578
Epoch 8/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0479 - loss: 3.2516 - val_accuracy: 0.0418 - val_loss: 3.2572
Epoch 9/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0486 - loss: 3.2516 - val_accuracy: 0.0378 - val_loss: 3.2580
Epoch 10/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0529 - loss: 3.2515 - val_accuracy: 0.0382 - val_loss: 3.2577
Epoch 11/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0501 - loss: 3.2494 - val_accuracy: 0.0398 - val_loss: 3.2576
Epoch 12/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0464 - loss: 3.2487 - val_accuracy: 0.0365 - val_loss: 3.2584
Epoch 13/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0529 - loss: 3.2481 - val_accuracy: 0.0429 - val_loss: 3.2569
Epoch 14/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0447 - loss: 3.2489 - val_accuracy: 0.0449 - val_loss: 3.2566
Epoch 15/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0464 - loss: 3.2492 - val_accuracy: 0.0388 - val_loss: 3.2588
Epoch 16/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0515 - loss: 3.2464 - val_accuracy: 0.0395 - val_loss: 3.2583
Epoch 17/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0513 - loss: 3.2481 - val_accuracy: 0.0372 - val_loss: 3.2606
Epoch 18/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0493 - loss: 3.2475 - val_accuracy: 0.0372 - val_loss: 3.2586
Epoch 19/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0514 - loss: 3.2464 - val_accuracy: 0.0355 - val_loss: 3.2586
Epoch 20/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0522 - loss: 3.2465 - val_accuracy: 0.0378 - val_loss: 3.2589

In [44]:
model3 = Sequential([
    Dense(56, activation='elu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model3.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model3.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

Epoch 1/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0418 - loss: 3.2715 - val_accuracy: 0.0378 - val_loss: 3.2653
Epoch 2/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0395 - loss: 3.2582 - val_accuracy: 0.0372 - val_loss: 3.2646
Epoch 3/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0416 - loss: 3.2598 - val_accuracy: 0.0452 - val_loss: 3.2622
Epoch 4/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0389 - loss: 3.2568 - val_accuracy: 0.0392 - val_loss: 3.2628
Epoch 5/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0402 - loss: 3.2564 - val_accuracy: 0.0388 - val_loss: 3.2632
Epoch 6/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0470 - loss: 3.2531 - val_accuracy: 0.0365 - val_loss: 3.2620
Epoch 7/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0477 - loss: 3.2532 - val_accuracy: 0.0368 - val_loss: 3.2668
Epoch 8/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0513 - loss: 3.2517 - val_accuracy: 0.0325 - val_loss: 3.2621
Epoch 9/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0474 - loss: 3.2531 - val_accuracy: 0.0412 - val_loss: 3.2627
Epoch 10/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0455 - loss: 3.2506 - val_accuracy: 0.0398 - val_loss: 3.2660
Epoch 11/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0528 - loss: 3.2498 - val_accuracy: 0.0422 - val_loss: 3.2639
Epoch 12/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0485 - loss: 3.2499 - val_accuracy: 0.0385 - val_loss: 3.2641
Epoch 13/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0515 - loss: 3.2511 - val_accuracy: 0.0395 - val_loss: 3.2643
Epoch 14/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0497 - loss: 3.2510 - val_accuracy: 0.0365 - val_loss: 3.2638
Epoch 15/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0498 - loss: 3.2499 - val_accuracy: 0.0398 - val_loss: 3.2625
Epoch 16/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0527 - loss: 3.2479 - val_accuracy: 0.0408 - val_loss: 3.2641
Epoch 17/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0517 - loss: 3.2478 - val_accuracy: 0.0395 - val_loss: 3.2656
Epoch 18/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0496 - loss: 3.2488 - val_accuracy: 0.0318 - val_loss: 3.2662
Epoch 19/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0503 - loss: 3.2478 - val_accuracy: 0.0362 - val_loss: 3.2661
Epoch 20/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0537 - loss: 3.2473 - val_accuracy: 0.0395 - val_loss: 3.2657

In [45]:
model4 = Sequential([
    Dense(56, activation='tanh', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model4.compile(optimizer='ADAgrad', loss='categorical_crossentropy', metrics=['accuracy'])
training = model4.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

Epoch 1/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0437 - loss: 3.2778 - val_accuracy: 0.0398 - val_loss: 3.2785
Epoch 2/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0401 - loss: 3.2706 - val_accuracy: 0.0392 - val_loss: 3.2730
Epoch 3/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0419 - loss: 3.2676 - val_accuracy: 0.0405 - val_loss: 3.2700
Epoch 4/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0393 - loss: 3.2651 - val_accuracy: 0.0408 - val_loss: 3.2682
Epoch 5/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0408 - loss: 3.2609 - val_accuracy: 0.0402 - val_loss: 3.2670
Epoch 6/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0402 - loss: 3.2625 - val_accuracy: 0.0402 - val_loss: 3.2662
Epoch 7/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0376 - loss: 3.2615 - val_accuracy: 0.0405 - val_loss: 3.2656
Epoch 8/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0367 - loss: 3.2626 - val_accuracy: 0.0395 - val_loss: 3.2652
Epoch 9/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0401 - loss: 3.2607 - val_accuracy: 0.0392 - val_loss: 3.2648
Epoch 10/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0400 - loss: 3.2597 - val_accuracy: 0.0378 - val_loss: 3.2646
Epoch 11/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0397 - loss: 3.2593 - val_accuracy: 0.0382 - val_loss: 3.2644
Epoch 12/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0382 - loss: 3.2596 - val_accuracy: 0.0382 - val_loss: 3.2642
Epoch 13/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0342 - loss: 3.2594 - val_accuracy: 0.0388 - val_loss: 3.2641
Epoch 14/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0391 - loss: 3.2591 - val_accuracy: 0.0398 - val_loss: 3.2640
Epoch 15/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0396 - loss: 3.2590 - val_accuracy: 0.0405 - val_loss: 3.2639
Epoch 16/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0434 - loss: 3.2584 - val_accuracy: 0.0395 - val_loss: 3.2638
Epoch 17/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0418 - loss: 3.2592 - val_accuracy: 0.0395 - val_loss: 3.2637
Epoch 18/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0412 - loss: 3.2577 - val_accuracy: 0.0395 - val_loss: 3.2636
Epoch 19/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0401 - loss: 3.2575 - val_accuracy: 0.0395 - val_loss: 3.2636
Epoch 20/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0410 - loss: 3.2596 - val_accuracy: 0.0388 - val_loss: 3.2635

# 4. Evaluation:

## Model 1

In [48]:
# Get the true labels
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model1.predict(x_test), axis=1)

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [49]:
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

In [50]:
print("Model with relu , softmax and adam optimizer ")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

Model with relu , softmax and adam optimizer
Accuracy: 0.035886448848419926
Precision: 0.017069048118527577
Recall: 0.035886448848419926
F1-score: 0.01829176427320269

## Model 2

In [51]:
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model2.predict(x_test), axis=1)

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [52]:
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

In [53]:
print("Model with relu , sigmoid and RMSprop")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

Model with relu , sigmoid and RMSprop
Accuracy: 0.0712372790573112
Precision: 0.034562267374272
Recall: 0.0712372790573112
F1-score: 0.042693125094824744

## Model 3

In [54]:
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model3.predict(x_test), axis=1)

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [55]:
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

In [56]:
print("Model with elu,sigmoid and RMSprop")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

Model with elu,sigmoid and RMSprop
Accuracy: 0.04124263524370648
Precision: 0.039269008211180435
Recall: 0.04124263524370648
F1-score: 0.03155048328699146

## Model 4

In [57]:
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model4.predict(x_test), axis=1)

117/117 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [58]:
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

In [59]:
print("Model with tanh and Adgrad ")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

Model with tanh and Adgrad
Accuracy: 0.06534547402249598
Precision: 0.0471346776796039
Recall: 0.06534547402249598
F1-score: 0.053559684435689814